### ISSUE TITLE
AttributeError: 'rtmidi._rtmidi.MidiIn' object has no attribute 'delete'

### ISSUE THREAD

**Issue by dimespi** [onlaj/Piano-LED-Visualizer#267]
@onlaj  I've updated the program but now I have this traceback when I start my raspberry: 

```
pi@raspberrypi(ro):~$ Namespace(clear=False, display=None, port=None, webinterface=None)
no input port
no play port
Traceback (most recent call last):
  File "/home/pi/Piano-LED-Visualizer/visualizer.py", line 85, in <module>
    menu = MenuLCD("menu.xml", args, usersettings, ledsettings, ledstrip, learning, saving, midiports)
  File "/home/pi/Piano-LED-Visualizer/lib/menulcd.py", line 45, in __init__
    self.update_ports()
  File "/home/pi/Piano-LED-Visualizer/lib/menulcd.py", line 122, in update_ports
    ports = mido.get_input_names()
  File "/home/pi/Downloads/mido/mido/backends/backend.py", line 169, in get_input_names
    devices = self._get_devices(**self._add_api(kwargs))
  File "/home/pi/Downloads/mido/mido/backends/backend.py", line 163, in _get_devices
    return self.module.get_devices(**self._add_api(kwargs))
  File "/home/pi/Downloads/mido/mido/backends/rtmidi.py", line 65, in get_devices
    mi.delete()
AttributeError: 'rtmidi._rtmidi.MidiIn' object has no attribute 'delete'
```

It worked fine before the update.

**Comment by onlaj** [comment]
Hello
Try to also update all required packages

`sudo pip3 install -r requirements.txt --upgrade`

**Comment by dimespi** [comment]
Thanks, works fine now! 

I have another issue, when I touch my midi keyboard the lights don't turn on. Here is my port settings:

![image](https://user-images.githubusercontent.com/31792531/140097672-f0210d00-833b-44c5-9f85-46bc1b624b1f.png)

When I try one of these animation it works though:

![image](https://user-images.githubusercontent.com/31792531/140098155-61b84eeb-99c2-4c7e-9e53-4bd6d232e4e0.png)

I'm using Ableton and the sound is working when I press a key.

**Comment by dimespi** [comment]
@onlaj Works fine now, thanks!
