### ISSUE TITLE
Trying a fresh manual install (without RTP and autoconnect and web interface)

### ISSUE THREAD

**Issue by AL1-1956** [onlaj/Piano-LED-Visualizer#427]
Hello
As title says , I try a manual install with a full version of bullseye .
Everything downloads OK 
upgrade done 
github cloned.

I do not want to have PLV start as a service because I want to be able to stop it and try to understand how it works

So I type
pi@raspberrypi:~ $ sudo python3 /home/Piano-LED-Visualizer/visualizer.py --webinterface false

And I get
Socket listening on: 192.168.1.18:8765
Traceback (most recent call last):
  File "/home/Piano-LED-Visualizer/visualizer.py", line 17, in <module>
    from webinterface import webinterface
  File "/home/Piano-LED-Visualizer/webinterface/__init__.py", line 43, in <module>
    from webinterface import views_api
  File "/home/Piano-LED-Visualizer/webinterface/views_api.py", line 3, in <module>
    from werkzeug.utils import safe_join
ImportError: cannot import name 'safe_join' from 'werkzeug.utils' (/usr/lib/python3/dist-packages/werkzeug/utils.py)
pi@raspberrypi:~ $

I do not understand what is going wrong , can you explain please ??
Thank You and have a nice day

Alain

**Comment by AL1-1956** [comment]
I made a little research and there is no (more?) such thing as "safe_join" in utils.py
I join the actual file

[utils.zip](https://github.com/onlaj/Piano-LED-Visualizer/files/10368426/utils.zip)

**Comment by AL1-1956** [comment]
It seems that 'safe_join' is (now?) in security.py

pi@raspberrypi:/usr/lib/python3/dist-packages/werkzeug $ grep safe_join *.py
security.py:def safe_join(directory, *pathnames):
pi@raspberrypi:/usr/lib/python3/dist-packages/werkzeug $

**Comment by AL1-1956** [comment]
Okay I modified the views_api.py and replaced "from werkzeug.utils" by "from werkzeug.security" and now PLV is working
so for me the case is closed .
