### ISSUE TITLE
from werkzeug.utils import safe_join

### ISSUE THREAD

**Issue by Sadvarsco** [onlaj/Piano-LED-Visualizer#450]
This is the error I get trying to run the visualizer

sudo python3 /home/Piano-LED-Visualizer/visualizer.py
Socket listening on: 192.168.2.10:8765
Traceback (most recent call last):
  File "/home/Piano-LED-Visualizer/visualizer.py", line 17, in <module>
    from webinterface import webinterface
  File "/home/Piano-LED-Visualizer/webinterface/__init__.py", line 43, in <modul                                                              e>
    from webinterface import views_api
  File "/home/Piano-LED-Visualizer/webinterface/views_api.py", line 3, in <modul                                                              e>
    from werkzeug.utils import safe_join
ImportError: cannot import name 'safe_join' from 'werkzeug.utils' (/usr/lib/pyth                                                              on3/dist-packages/werkzeug/utils.py)

Can anyone help me? I think if I just disable web interface itll work, but I was planning on relying on that.

**Comment by Sadvarsco** [comment]
I ended up changing "werkzeug.utils" to "werkzeug.security"
